import 'dart:io';

import 'package:dio/dio.dart';
import 'package:json_annotation/json_annotation.dart';


import 'package:chest_disease_app/features/scan/domain/entities/chest_prediction_entity.dart';



/// The request model used to upload the scan data.
/// This remains as it is needed by the repository.
class UploadScanRequestModel {
  final double long;
  final double lat;
  final File image;

  const UploadScanRequestModel({
    required this.long,
    required this.lat,
    required this.image,
  });

  Future<FormData> toFormData() async {
    FormData formData = FormData.fromMap({
      "Longitude": long,
      "Latitude": lat,
    });
    formData.files.add(
      MapEntry(
        "image", // Key must match the backend API
        await MultipartFile.fromFile(
          image.path,
          filename: image.path.split('/').last,
        ),
      ),
    );
    return formData;
  }
}

/// The response model for the chest prediction API call.
/// This class is designed to be generated by json_serializable.

class ChestPredictionModel {
  final String prediction;
  final double confidence;
  final String description;
  @JsonKey(name: 'heatmap_base64')
  final String? heatmapBase64;

  const ChestPredictionModel({
    required this.prediction,
    required this.confidence,
    required this.description,
    this.heatmapBase64,
  });

  factory ChestPredictionModel.fromJson(Map<String, dynamic> json) {
    return ChestPredictionModel(
      prediction: json['prediction'] as String,
      confidence: (json['confidence'] as num).toDouble(),
      description: json['description'] as String,
      heatmapBase64: json['heatmap_base64'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'prediction': prediction,
      'confidence': confidence,
      'description': description,
      'heatmap_base64': heatmapBase64,
    };
  }

  /// Maps the Data Transfer Object (DTO) to a Domain Entity.
  ChestPredictionEntity toEntity() {
    return ChestPredictionEntity(
      prediction: prediction,
      confidence: confidence,
      description: description,
      heatmapBase64: heatmapBase64,
    );
  }
}

